#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#1e1e2e"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#7ccdfd"
bspc config presel-feedback_colour "#fc9d63"
