#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config focused_border_color "#efefef"
bspc config normal_border_color "#6e6a86"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

