xsetroot -cursor_name left_ptr &
#setxkbmap -layout us,ru -option grp:shifts_toggle &
feh --bg-scale ~/.config/bspwm/wall.jpg &
picom --config ~/.config/picom/picom.conf &
#xrandr --output HDMI-0 --mode 1920x1080 --rate 75 &
polybar -r &
exec bspwm
